openapi: 3.0.0
info:
  title: 'API da prova tray'
  description: 'Essa API cadastra vendedores e vendas.'
  contact:
    email: guilhermemaiasilva@hotmail.com
  version: 1.0.0
paths:
  /vendedor/lista:
    get:
      tags:
        - Vendedor
      summary: 'Obtém todas os vendedores'
      operationId: 'App\Http\Controllers\UsuariosController::index'
      responses:
        '200':
          description: 'Retorna uma lista de vendedores'
        '500':
          description: 'Erro interno da API, consulte o log'
  /vendedor/incluir:
    post:
      tags:
        - Vendedor
      summary: 'Insere um novo vendedor'
      description: 'Inclui um novo vendedor'
      operationId: addNovoVendedor
      requestBody:
        description: 'Dados do vendedor que deve ser armazenado.'
        required: true
        content:
          multipart/form-data: {  }
      responses:
        '200':
          description: 'Objeto com os dados do vendedor'
        '500':
          description: 'Erro interno da API, consulte o log'
  /venda/lista:
    get:
      tags:
        - Vendas
      summary: 'Obtém todas as vendas'
      operationId: 'App\Http\Controllers\VendasController::index'
      responses:
        '200':
          description: 'Retorna uma lista de todas as vendas'
        '500':
          description: 'Erro interno da API, consulte o log'
  /venda/incluir:
    post:
      tags:
        - Venda
      summary: 'Insere uma nova venda'
      description: 'Inclui uma nova venda'
      operationId: addNovaVenda
      requestBody:
        description: 'Dados da venda que deve ser armazenado.'
        required: true
        content:
          multipart/form-data: {  }
      responses:
        '200':
          description: 'Objeto com os dados da empresa'
        '500':
          description: 'Erro interno, consulte o log'
